-- ════════════════════════════════════════════════════════════════
-- Cypher Cache — Phase 4 (admin management)
-- Run in the Supabase SQL editor. Safe to run more than once.
-- ════════════════════════════════════════════════════════════════

-- 1. Seed the protected base admin with an unguessable sentinel hash.
--    The account is DORMANT — nobody can log in until you set a real password
--    (step 2). Idempotent: only inserts if the email isn't already present.
insert into clients (name, email, role, password_hash)
select 'Cypher Admin', 'cypher@cypher.audio', 'admin', 'locked_b3f9a1c2d4e6'
where not exists (select 1 from clients where lower(email) = 'cypher@cypher.audio');

-- 2. SET YOUR REAL PASSWORD (do this once).
--    a) Open your browser console on any page and run this, replacing the
--       password with your own. It prints a short hex hash:
--
--       (p => { let h=0; for(let i=0;i<p.length;i++){h=((h<<5)-h)+p.charCodeAt(i);h|=0} return h.toString(16) })('YOUR_PASSWORD')
--
--    b) Paste the printed hash into this update and run it:
--
--    update clients set password_hash = 'PASTE_YOUR_HASH_HERE'
--    where lower(email) = 'cypher@cypher.audio';

-- 3. One-time cleanup: remove events generated by ANY admin account during
--    testing, so Insights reflects client activity only.
delete from track_events
where client_id in (select id from clients where role = 'admin');
